fixtures:
  repositories:
    limits: 'https://github.com/miguno/puppet-limits.git'
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.1.0'
    supervisor: 'https://github.com/miguno/puppet-supervisor'
    vcsrepo: 'https://github.com/puppetlabs/puppetlabs-vcsrepo'
  symlinks:
    blueflood: "#{source_dir}"
